#!/bin/bash

unitAddress()
{
    py_script="
import sys
import yaml

status_yaml=yaml.load(sys.stdin)
print(status_yaml['applications']['ghost']['units']['ghost/0']['public-address'])
"
    juju status ghost/0 --format yaml | env python3 -c "$py_script"
}


grep -q 'DISTRIB_CODENAME=xenial' /etc/lsb-release || (printf "Wrong series\n" && exit 0)
juju version|grep -qP '^2\.\d' || (printf "Wrong juju version, needs to be 2.0 or higher\n" && exit 0)

conjure-up -d ./ghost-spell localhost || exit 1

curl --silent $(unitAddress)|grep -qP 'Welcome\sto\sGhost' || exit 1
