#!/bin/bash

unitAddress()
{
    py_script="
import sys
import yaml

status_yaml=yaml.load(sys.stdin)
unit = status_yaml['applications'][$1]['units'][0]
print(unit['public-address'])
"
    juju status $1 --format yaml | env python3 -c "$py_script"
}

juju deploy cs:ghost-16
juju wait

curl --silent $(unitAddress "ghost")|grep -qP 'Welcome\sto\sGhost' || exit 1

juju deploy mysql
juju deploy haproxy
juju add-relation mysql ghost
juju add-relation haproxy ghost
juju wait

curl --silent $(unitAddress "haproxy")|grep -qP 'Welcome\sto\sGhost' || exit 1

juju config ghost port=8888
juju wait

curl --silent $(unitAddress "haproxy")|grep -qP 'Welcome\sto\sGhost' || exit 1
