#!/bin/bash

unitAddress()
{
    py_script="
import sys
import yaml

status_yaml=yaml.load(sys.stdin)
print(status_yaml['applications']['ghost']['units']['ghost/0']['public-address'])
"
    juju status ghost/0 --format yaml | env python3 -c "$py_script"
}

juju deploy .
juju wait

curl --silent $(unitAddress)|grep -qP 'Welcome\sto\sGhost' || exit 1
